spring.application.name=multi_tenant_task
spring.datasource.url=jdbc:mysql://localhost:3306/tenant_task
spring.datasource.password=ifeoluwa2443
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sayoakinlade211@gmail.com
spring.mail.password=fshx uxwj gljo qtbk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.data.redis.host=localhost
spring.data.redis.port=6379


cloudinary.cloud.name=dppc8uabz
cloudinary.api.key=961763246558291
cloudinary.secret.key=yt5cgD--oo9uxF6XXZbLm9uUrmI

mubaro.api.key=mubaro_live_052b45b7739bf4cb6597d5c7b4462fb94336266d75e3a28f

app.jwt.secret=1LiOUj6PEEUAVbNeIKt3cL052UBMDQPUS5/HQZwb9zk=
app.jwt.expiration=3600000
app.jwt.refresh-expiration=48600000
